name: Dev test

on:
  workflow_dispatch: {}

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11" ]

    name: Python  ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip install pytest
          pip install -e .
          pip install -r tests/requirements.txt
          pip freeze

      - name: Tests
        run: pytest tests/test_examples.py
